### ISSUE TITLE
oopsy install on MacOS 11.3 Big Sur gcc issues

### ISSUE THREAD

**Issue by ahause23** [electro-smith/oopsy#49] opened 2021-04-28 23:07 UTC
Hi,
I have installed all the toolchain components on MacOS Big Sur verified by successfully running the following:

make --version
arm-none-eabi-gcc --version
dfu-util --version
openocd --version

When pushing a gen patch (reverb example) to the daisy pod from Max 8 the console outputs:
 
oopsy-verbose: /bin/sh: arm-none-eabi-gcc: command not found
oopsy-verbose: make: *** [build/system_stm32h7xx.o] Error 127
oopsy-verbose: make failed

The daisy web programmer works as expected and running the same process on my aging 2013 macbook air worked OS 10.13.6

Are there some different install methods required for Mac OS Big Sur?
Of note when I open a terminal on my old computer and navigate to ../usr/local I can see Homebrew and Caskroom and many other folders. On my new computer when I navigate to ../usr/local it is empty.

Pls let me know what i should try,
thanks,
Adrian

**Comment by grrrwaaa** [comment] 2021-04-29 13:13
Do the notes under https://github.com/electro-smith/oopsy/issues/37 help?

**Comment by ahause23** [comment] 2021-04-30 00:02
Thanks Graham, 
It kinda makes sence but im not sure what exactly to do. 
I tried adding the below referenced code to the beginning of the oopsy.js file and re-ran ../Max 8/Packages/oopsy/install.sh.   
```

let build_tools_path;
function checkBuildEnvironment() {
	// check for available build tools:
	if (os.platform == "win32") {
		// TODO
	} else {
		// OSX:
		let locations = ["/opt/homebrew/bin", "/usr/local/bin"]
		for (loc of locations) {
			if (fs.existsSync(`${loc}/arm-none-eabi-gcc`)) {
				build_tools_path = loc;
				console.log(`using build tools found in ${build_tools_path}`);
				break;
			}
		}
		if (!build_tools_path) {
			console.log("oopsy can't find an ARM-GCC toolchain. Please check https://github.com/electro-smith/DaisyWiki/wiki/1e.-Getting-Started-With-Oopsy-(Gen~-Integration) for installation instructions.")
			process.exit(-1);
		}
		if (!fs.existsSync(`${build_tools_path}/dfu-util`)) {
			console.warn(`oopsy can't find the dfu-util binary in ${build_tools_path}, will not be able to upload binary to the Daisy. Please check https://github.com/electro-smith/DaisyWiki/wiki/1e.-Getting-Started-With-Oopsy-(Gen~-Integration) for installation instructions.`)
		}
	}
}
```

This resulted in the same error in Max when flashing the Daisy Pod with the Reverb sample code.
Are you able to give more of a detailed instruction?
Many thanks,
Adrian

**Comment by mmake** [comment] 2021-04-30 06:39
I have the exact same problem as OP. Trying to upload example Reverb to a Daisy Patch on a M1 Minimac:

oopsy-verbose: /bin/sh: arm-none-eabi-gcc: command not found
oopsy-verbose: make: *** [build/system_stm32h7xx.o] Error 127
oopsy-verbose: make failed

My toolchain components also verify

,Marko

**Comment by grrrwaaa** [comment] 2021-04-30 21:36
Hi mmake -- I'm passing this to @stephenhensley as he's been working through the build toolchain stuff with much more detail than me, I'm sure he can help!

**Comment by mmake** [comment] 2021-05-01 05:50
Thank you both! @stephenhensley informed me on Slack that i need to run `./install sh` to populate the folder where that file lives. I think that might be the cause for my error

**Comment by ahause23** [comment] 2021-05-01 10:48
Hi Marco,
did this work for you? pls let me know the process you used.
Thanks,
Ade

**Comment by mmake** [comment] 2021-05-01 11:23
@ahause23 I followed these instructions:

# first open a console in your Documents/Max 8/Packages folder, then:
git clone https://github.com/electro-smith/oopsy.git
cd oopsy
git checkout dev
./install.sh

Also to verify the toolchain components are correctly installed:

make --version
arm-none-eabi-gcc --version
dfu-util --version

Seems to work but i didn't try with the actual module yet.

**Comment by ahause23** [comment] 2021-05-03 03:28
Thanks Marco, 
After renaming the current ../oopsy folder to ../oopsy_old I tried your steps but get errors in the output.

Suggested install process Terminal output below.

```
color@192-168-1-139 Packages % git clone https://github.com/electro-smith/oopsy.git
Cloning into 'oopsy'...
remote: Enumerating objects: 1311, done.
remote: Counting objects: 100% (717/717), done.
remote: Compressing objects: 100% (418/418), done.
remote: Total 1311 (delta 521), reused 470 (delta 288), pack-reused 594
Receiving objects: 100% (1311/1311), 512.97 KiB | 3.66 MiB/s, done.
Resolving deltas: 100% (943/943), done.
color@192-168-1-139 Packages % cd oopsy
color@192-168-1-139 oopsy % git checkout dev

Branch 'dev' set up to track remote branch 'dev' from 'origin'.
Switched to a new branch 'dev'
color@192-168-1-139 oopsy % ./install.sh
/Users/color/Documents/Max 8/Packages/oopsy
get submodules
Submodule 'source/libdaisy' (https://github.com/electro-smith/libDaisy.git) registered for path 'source/libdaisy'
Cloning into '/Users/colorone/Documents/Max 8/Packages/oopsy/source/libdaisy'...
Submodule path 'source/libdaisy': checked out '3dda55e9ed55a2f8b6bc4fa6aa2c7ae134c317ab'
rebuilding everything. . . 
only errors, and warnings will output. . . 
-------------------
rebuilding libdaisy
arm-none-eabi-gcc: fatal error: Killed: 9 signal terminated program cc1
arm-none-eabi-gcc: fatal error: Killed: 9 signal terminated program cc1
arm-none-eabi-gcc: fatal error: Killed: 9 signal terminated program cc1
compilation terminated.
compilation terminated.
compilation terminated.
arm-none-eabi-gcc: fatal error: Killed: 9 signal terminated program cc1
compilation terminated.
make: *** [build/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cec.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [build/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.o] Error 1
make: *** [build/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.o] Error 1
make: *** [build/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.o] Error 1
done building libdaisy
color@192-168-1-139 oopsy % 

```
$make --version                                  is 3.81
$dfu-util --version                               is 0.10
$arm-none-eabi-gcc --version          is 10.2.1 20201103 (release)

Max still reports the same 'arm' errors when compiling the patch. 

```
oopsy-verbose: 
oopsy-verbose: /bin/sh: arm-none-eabi-gcc: command not found
oopsy-verbose: make: *** [build/system_stm32h7xx.o] Error 127
oopsy-verbose: make failed
oopsy-verbose: oopsy done
```
Any further assistance in helping me resolve this would be much appreciated :)

Thanks,
Adrian

**Comment by ahause23** [comment] 2021-05-03 04:17
Ok, I had to delete the 'oopsy_old' folder as it was still linking to it. 
Now with in Max I see what looks like the Dev bpatcher. 
My output compile error now lists  the below, hopefully this helps in finding my problem:

```
gen~: exported: Macintosh HD:/Users/color/Documents/Max 8/Packages/oopsy/examples/reverb.cpp
oopsy-verbose: script start patch 48kHz block48 /Users/color/Documents/Max 8/Packages/oopsy/examples/reverb.cpp boost fastmath
oopsy-verbose: stop success dictionary u023000871
oopsy-verbose: start success dictionary u625000872
oopsy-verbose: using build tools found in /opt/homebrew/bin
oopsy-verbose: Target patch configured in path /Users/color/Documents/Max 8/Packages/oopsy/source/daisy.patch.json
oopsy-verbose: Building to /Users/color/Documents/Max 8/Packages/oopsy/source/build_reverb_patch
oopsy-verbose: Will upload from /Users/color/Documents/Max 8/Packages/oopsy/examples/reverb.cpp by writing to:
oopsy-verbose: 	/Users/color/Documents/Max 8/Packages/oopsy/source/build_reverb_patch/reverb_patch.cpp
oopsy-verbose: 	/Users/color/Documents/Max 8/Packages/oopsy/source/build_reverb_patch/Makefile
oopsy-verbose: 	/Users/color/Documents/Max 8/Packages/oopsy/source/build_reverb_patch/build/reverb.bin
oopsy-verbose: oopsy generated code
oopsy-verbose: generated code
oopsy-verbose: compiling...
oopsy-verbose: oopsy compiling...
oopsy-verbose: oopsy compiler error
oopsy-verbose: compiler error
oopsy-verbose: Error: Command failed: export PATH=$PATH:/opt/homebrew/bin && make clean && make
oopsy-verbose: /opt/homebrew/Caskroom/gcc-arm-embedded/10-2020-q4-major/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: cannot find -ldaisy
oopsy-verbose: collect2: error: ld returned 1 exit status
oopsy-verbose: make: *** [build/reverb.elf] Error 1
oopsy-verbose: 
oopsy-verbose:     at ChildProcess.exithandler (child_process.js:295:12)
oopsy-verbose:     at ChildProcess.emit (events.js:223:5)
oopsy-verbose:     at maybeClose (internal/child_process.js:1021:16)
oopsy-verbose:     at Socket.<anonymous> (internal/child_process.js:430:11)
oopsy-verbose:     at Socket.emit (events.js:223:5)
oopsy-verbose:     at Pipe.<anonymous> (net.js:664:12) {
oopsy-verbose:   killed: false,
oopsy-verbose:   code: 2,
oopsy-verbose:   signal: null,
oopsy-verbose:   cmd: 'export PATH=$PATH:/opt/homebrew/bin && make clean && make'
oopsy-verbose: }
oopsy-verbose: /opt/homebrew/Caskroom/gcc-arm-embedded/10-2020-q4-major/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: cannot find -ldaisy
oopsy-verbose: collect2: error: ld returned 1 exit status
oopsy-verbose: make: *** [build/reverb.elf] Error 1
oopsy-verbose: 

```
Thanks,
Adrian

**Comment by grrrwaaa** [comment] 2021-05-03 12:04
Did you run ./install.sh from the oopsy folder? That is what creates the
daisy library (what -ldaisy is looking for). If there were errors running
install.sh that would be helpful to see.

**Comment by ahause23** [comment] 2021-05-03 21:35
Thanks Graham,
I tried running ./install.sh again this morning and had to override a few gcc items in preferences/security.
this resulted in a successful instal.
```
color@192-168-1-116 oopsy % ./install.sh
/Users/color/Documents/Max 8/Packages/oopsy
get submodules
rebuilding everything. . . 
only errors, and warnings will output. . . 
-------------------
rebuilding libdaisy
arm-none-eabi-ar: creating build/libdaisy.a
done building libdaisy

```
Moving back to Max I again had to set some more security overrides when attempting a flash but now I get what appears to be a successful flashing of the Dailsy Petal.  Im at home so I cant check the validity of the flash but will check later. 
The output snippet from Max now only gives some warnings about invalid DFU suffix signature:
```
oopsy-verbose: Download done.
oopsy-verbose: File downloaded successfully
oopsy-verbose: 
oopsy-verbose: stderr dfu-util: Warning: Invalid DFU suffix signature
oopsy-verbose: dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
oopsy-verbose: dfu-util: Error during download get_status
oopsy-verbose: make: *** [program-dfu] Error 74
oopsy-verbose: 
oopsy-verbose: oopsy flashed

```
Full output below.
```
oopsy-verbose: script start petal 48kHz block48 /Users/color/Documents/Max 8/Packages/oopsy/examples/reverb.cpp boost
oopsy-verbose: stop success dictionary u416000825
oopsy-verbose: start success dictionary u319000826
oopsy-verbose: using build tools found in /opt/homebrew/bin
oopsy-verbose: Target petal configured in path /Users/color/Documents/Max 8/Packages/oopsy/source/daisy.petal.json
oopsy-verbose: Building to /Users/color/Documents/Max 8/Packages/oopsy/source/build_reverb_petal
oopsy-verbose: Will upload from /Users/color/Documents/Max 8/Packages/oopsy/examples/reverb.cpp by writing to:
oopsy-verbose: 	/Users/color/Documents/Max 8/Packages/oopsy/source/build_reverb_petal/reverb_petal.cpp
oopsy-verbose: 	/Users/color/Documents/Max 8/Packages/oopsy/source/build_reverb_petal/Makefile
oopsy-verbose: 	/Users/color/Documents/Max 8/Packages/oopsy/source/build_reverb_petal/build/reverb.bin
oopsy-verbose: oopsy generated code
oopsy-verbose: generated code
oopsy-verbose: compiling...
oopsy-verbose: oopsy compiling...
oopsy-verbose: oopsy created binary 59KB
oopsy-verbose: created binary 59KB
oopsy-verbose: flashing...
oopsy-verbose: oopsy flashing...
oopsy-verbose: stdout dfu-util -a 0 -s 0x08000000:leave -D build/reverb.bin -d ,0483:df11
oopsy-verbose: dfu-util 0.10
oopsy-verbose: 
oopsy-verbose: flashed
oopsy-verbose: Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
oopsy-verbose: Copyright 2010-2020 Tormod Volden and Stefan Schmidt
oopsy-verbose: This program is Free Software and has ABSOLUTELY NO WARRANTY
oopsy-verbose: Please report bugs to http://sourceforge.net/p/dfu-util/tickets/
oopsy-verbose: 
oopsy-verbose: Opening DFU capable USB device...
oopsy-verbose: ID 0483:df11
oopsy-verbose: Run-time device DFU version 011a
oopsy-verbose: Claiming USB DFU Interface...
oopsy-verbose: Setting Alternate Setting #0 ...
oopsy-verbose: Determining device status: state = dfuIDLE, status = 0
oopsy-verbose: dfuIDLE, continuing
oopsy-verbose: DFU mode device DFU version 011a
oopsy-verbose: Device returned transfer size 1024
oopsy-verbose: DfuSe interface name: "Internal Flash   "
oopsy-verbose: Downloading element to address = 0x08000000, size = 59936
oopsy-verbose: Erase   	[                         ]   0%            0 bytesErase   	[                         ]   0%            0 bytesErase   	[=                        ]   5%         3072 bytesErase   	[==                       ]   8%         5120 bytesErase   	[===                      ]  13%         8192 bytesErase   	[====                     ]  17%        10240 bytesErase   	[=====                    ]  20%        12288 bytesErase   	[======                   ]  25%        15360 bytesErase   	[=======                  ]  29%        17408 bytesErase   	[========                 ]  32%        19456 bytesErase   	[=========                ]  37%        22528 bytesErase   	[==========               ]  41%        24576 bytesErase   	[===========              ]  44%        26624 bytesErase   	[============             ]  49%        29696 bytesErase   	[=============            ]  52%        31744 bytesErase   	[==============           ]  56%        33792 bytesErase   	[===============          ]  61%        36864 bytesErase   	[================         ]  64%        38912 bytesErase   	[=================        ]  68%        40960 bytesErase   	[==================       ]  73%        44032 bytesErase   	[===================      ]  76%        46080 bytesErase   	[====================     ]  80%        48128 bytesErase   	[=====================    ]  85%        51200 bytesErase   	[======================   ]  88%        53248 bytesErase   	[=======================  ]  92%        55296 bytesErase   	[======================== ]  97%        58368 bytesErase   	[=========================] 100%        59936 bytes
oopsy-verbose: Erase    done.
oopsy-verbose: Download	[                         ]   0%            0 bytesDownload	[                         ]   3%         2048 bytesDownload	[=                        ]   5%         3072 bytesDownload	[==                       ]   8%         5120 bytesDownload	[===                      ]  13%         8192 bytesDownload	[===                      ]  15%         9216 bytesDownload	[====                     ]  17%        10240 bytesDownload	[=====                    ]  20%        12288 bytesDownload	[======                   ]  25%        15360 bytesDownload	[======                   ]  27%        16384 bytesDownload	[=======                  ]  29%        17408 bytesDownload	[========                 ]  32%        19456 bytesDownload	[=========                ]  37%        22528 bytesDownload	[=========                ]  39%        23552 bytesDownload	[==========               ]  41%        24576 bytesDownload	[===========              ]  44%        26624 bytesDownload	[============             ]  49%        29696 bytesDownload	[=============            ]  52%        31744 bytesDownload	[==============           ]  56%        33792 bytesDownload	[===============          ]  61%        36864 bytesDownload	[================         ]  64%        38912 bytesDownload	[=================        ]  68%        40960 bytesDownload	[==================       ]  73%        44032 bytesDownload	[===================      ]  76%        46080 bytesDownload	[====================     ]  80%        48128 bytesDownload	[=====================    ]  85%        51200 bytesDownload	[======================   ]  88%        53248 bytesDownload	[=======================  ]  92%        55296 bytesDownload	[======================== ]  97%        58368 bytesDownload	[=========================] 100%        59936 bytes
oopsy-verbose: Download done.
oopsy-verbose: File downloaded successfully
oopsy-verbose: 
oopsy-verbose: stderr dfu-util: Warning: Invalid DFU suffix signature
oopsy-verbose: dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
oopsy-verbose: dfu-util: Error during download get_status
oopsy-verbose: make: *** [program-dfu] Error 74
oopsy-verbose: 
oopsy-verbose: oopsy flashed

```
I test the patch at the office later and reply back.
thanks,
Adrian

**Comment by stephenhensley** [comment] 2021-05-03 23:44
@ahause23 out of curiosity did you install the toolchain (arm-none-eabi, dfu-util, etc.) through brew directly or by using the `install.command` from the [DaisyToolchain](https://github.com/electro-smith/DaisyToolchain) repository.

The latter should do the security overrides that are necessary internally. Just want to make sure it's functioning properly if that's what you used.

**Comment by takumi-ogata** [comment] 2023-03-04 19:04
Hey Adrian, 

We are just checking by to see if this is still an issue for you. Let us know! Thanks.

**Comment by ahause23** [comment] 2023-03-08 06:56
This was resolved thank you.

**Comment by takumi-ogata** [comment] 2023-03-08 15:50
This issue was resolved with presented troubleshooting solutions, such as running ./install.sh from the oopsy folder and overriding few gcc items in preferences/security.

**Closed by takumi-ogata** 2023-03-08 15:50 UTC
